version: '3.9'

services:
    nginx:
        build: ./nginx
        ports:
            - 443:443
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./nginx/tools/ssl:/etc/ssl
            - ./nginx/index.html:/usr/share/nginx/html/index.html
