services:
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - '443:443'
        volumes:
            - ./nginx/tools/ssl:/etc/ssl
            - wordpress_data:/var/www/html
        depends_on:
            - wordpress
        networks:
            - inception-network

    wordpress:
        build: ./wordpress
        container_name: wordpress
        expose:
            - '9000'
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception-network
        depends_on:
            - mariadb
        environment:
          WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
          WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
          WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
          WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

    mariadb:
        build: ./mariadb
        container_name: mariadb
        expose:
            - '3306'
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception-network
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
    wordpress_data:
    mariadb_data:

networks:
    inception-network:
        driver: bridge
