services:
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - '443:443'
        volumes:
            - ./nginx/tools/ssl:/etc/ssl
            - wordpress_data:/var/www/html
        depends_on:
            - wordpress
        networks:
            - inception-network
        restart: on-failure

    wordpress:
        build: ./wordpress
        container_name: wordpress
        expose:
            - '9000'
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception-network
        depends_on:
            - mariadb
        environment:
            - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST 
            - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
            - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD 
            - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
            - WORDPRESS_ADMIN_USERNAME=$WORDPRESS_ADMIN_USERNAME 
            - WORDPRESS_ADMIN_PASSWORD=$WORDPRESS_ADMIN_PASSWORD
            - WORDPRESS_ADMIN_EMAIL=$WORDPRESS_ADMIN_EMAIL
            - WORDPRESS_USER_USERNAME=$WORDPRESS_USER_USERNAME
            - WORDPRESS_USER_PASSWORD=$WORDPRESS_USER_PASSWORD 
            - WORDPRESS_USER_EMAIL=$WORDPRESS_USER_EMAIL
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
        restart: on-failure

    mariadb:
        build: ./mariadb
        container_name: mariadb
        expose:
            - '3306'
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception-network
        restart: on-failure

volumes:
    wordpress_data:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            device: /home/pclaus/data/wordpress
            o: bind
    mariadb_data:
        name: mariadb
        driver: local
        driver_opts:
            type: none
            device: /home/pclaus/data/mariadb
            o: bind

networks:
    inception-network:
        driver: bridge
